- name: add neovim repository
  apt_repository: repo='ppa:neovim-ppa/stable'
- name: add fish repository
  apt_repository: repo='ppa:fish-shell/release-2'
- name: install base packages
  apt: pkg={{item}} update_cache=yes
  with_items:
    - build-essential
    - git
    - mercurial
    - libpq-dev
    - unzip
    - gdal-bin
    - python
    - python-dev
    - virtualenv
    - libxslt-dev
    - tmux
    - tree
    - fish
    - silversearcher-ag
    - docker-compose
    - python3-pip
    - python-pip
    - neovim

- name: checkout config
  git: repo=https://github.com/jamesturk/config.git dest=/home/james/config accept_hostkey=yes version=master
  become_user: "james"
- name: make directories
  file: state=directory path=/home/james/{{item}}
  become_user: "james"
  with_items:
    - .config
    - .virtualenvs
- name: link config
  file: state=link path={{item.path}} src={{item.src}}
  become_user: "james"
  with_items:
    - { path: /home/james/.gitconfig, src: /home/james/config/dotfiles/gitconfig }
    - { path: /home/james/.tmux.conf, src: /home/james/config/dotfiles/tmux.conf }
    - { path: /home/james/.config/fish, src: /home/james/config/dotfiles/config/fish }
    - { path: /home/james/.config/git, src: /home/james/config/dotfiles/config/git }
    - { path: /home/james/.config/nvim, src: /home/james/config/dotfiles/config/nvim }

# - user:
#     name: james
#     generate_ssh_key: yes
#     ssh_key_bits: 4096
#     ssh_key_file: .ssh/id_rsa

# python stuff
- name: install python global packages
  pip: name={{item}} executable=pip3
  become_user: "james"
  with_items:
    - virtualfish
    - flake8
- name: install neovim requirements (python 2)
  pip: name=neovim virtualenv=/home/james/.virtualenvs/neovim2 virtualenv_python=python2
  become_user: "james"
- name: install neovim requirements (python 3)
  pip: name=neovim virtualenv=/home/james/.virtualenvs/neovim3 virtualenv_python=python3
  become_user: "james"

# SSH config
- name: fix SSH port
  replace: 
    path: /etc/ssh/sshd_config
    regexp: 'Port 22'
    replace: 'Port {{new_ssh_port}}'
    # TODO: restart ssh

# UFW firewall
- name: allow SSH
  ufw: rule=allow port={{new_ssh_port}} proto=tcp
- name: UFW logging on
  ufw: logging=on
- name: UFW enabled & disallowing everything
  ufw: state=enabled policy=deny
